# Базируемся на официальном образе PostgreSQL
FROM postgres:16

# Устанавливаем переменные окружения (если хочешь по дефолту)
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin
ENV POSTGRES_DB=userdatabase
